Improve dag triggering for versions before 2.3.0

diff --git a/whirl b/whirl
--- a/whirl
+++ b/whirl
@@ -116,7 +116,7 @@ detect_potential_dag() {
 check_next_dagrun_scheduled_today() {
   local DAG_ID=$1
   echo "Checking next dagrun for ${DAG_ID}" >&2
-  result=$(curl -s -u admin:admin "http://localhost:${AIRFLOW_UI_PORT}/api/v1/dags/${DAG_ID}" | jq '.next_dagrun | split("T") | .[0] | strptime("%Y-%m-%d") | strftime("%Y%m%d") | tonumber - (now | strftime("%Y%m%d") | tonumber)')
+  result=$(curl -s -u admin:admin "http://localhost:${AIRFLOW_UI_PORT}/api/v1/dags/${DAG_ID}" | jq '.next_dagrun // (now | todate) | split("T") | .[0] | strptime("%Y-%m-%d") | strftime("%Y%m%d") | tonumber - (now | strftime("%Y%m%d") | tonumber)')
   echo "Result of checking next dagrun for ${DAG_ID} is ${result} (days from now)" >&2
   if [ "${result}" -eq 0 ]; then
     true
@@ -185,6 +185,45 @@ run_compose_setup_scripts() {
       # shellcheck disable=SC1090
       . "$filename"
     done
+  fi
+}
+
+check_dagrun_result() {
+  local DAG_ID=${1}
+  local RETRY=${2:-true}
+
+  while [ "$(test_dag_state "${DAG_ID}" "running")" -gt 0 ]; do
+    echo "Dag '${DAG_ID}' is (still) running..."
+    sleep 5;
+  done
+  SUCCES_STATE="success"
+  FAILURE_STATE="failed"
+  if [ "${WHIRL_CI_EXPECT_FAILURE}" == true ]; then
+    SUCCES_STATE="failed"
+    FAILURE_STATE="success"
+  fi
+  if [ "$(test_dag_state "${DAG_ID}" "${SUCCES_STATE}")" -ge 1 ]; then
+    echo "Dag '${DAG_ID}' run(s) successfully finished"
+    stop
+    return 0
+  fi
+  if [ "$(test_dag_state "${DAG_ID}" "${FAILURE_STATE}")" -ge 1 ]; then
+    echo "Dag '${DAG_ID}' run(s) failed"
+    # output dagrun result
+    test_dag_state "${DAG_ID}" "${FAILURE_STATE}" true
+    return 1
+  else
+    echo "Dag '${DAG_ID}' neither success nor failed!!!"
+    if ${RETRY}; then
+      echo "Maybe there was no dagrun for dag ${DAG_ID}. Retry after manual trigger"
+      trigger_dagrun "${DAG_ID}"
+      check_dagrun_result "${DAG_ID}" false
+    else
+      # output dagrun result
+      test_dag_state "${DAG_ID}" "${FAILURE_STATE}" true
+      debug_log_airflow
+      return 7
+    fi
   fi
 }
 
@@ -260,39 +299,9 @@ start() {
               echo "Need to trigger the dag ${DAG_ID} since first scheduled time is later than today and unpause is not enough to start running"
               trigger_dagrun "${DAG_ID}"
           fi
-          while [ "$(test_dag_state "${DAG_ID}" "running")" -gt 0 ]; do
-            echo "Dag '${DAG_ID}' is (still) running..."
-            sleep 5;
-          done
-          SUCCES_STATE="success"
-          FAILURE_STATE="failed"
-          if [ "${WHIRL_CI_EXPECT_FAILURE}" == true ]; then
-            SUCCES_STATE="failed"
-            FAILURE_STATE="success"
-          fi
-          if [ "$(test_dag_state "${DAG_ID}" "${SUCCES_STATE}")" -ge 1 ]; then
-            echo "Dag '${DAG_ID}' run(s) successfully finished"
-            stop
-            exit 0
-          fi
-          if [ "$(test_dag_state "${DAG_ID}" "${FAILURE_STATE}")" -ge 1 ]; then
-            echo "Dag '${DAG_ID}' run(s) failed"
-            # output dagrun result
-            test_dag_state "${DAG_ID}" "${FAILURE_STATE}" true
-            if [ "$STOP_ON_FAILURE" = true ]; then
-              stop
-              exit 1
-            fi
-          else
-            echo "Dag '${DAG_ID}' neither success nor failed!!!"
-            # output dagrun result
-            test_dag_state "${DAG_ID}" "${FAILURE_STATE}" true
-            debug_log_airflow
-            if [ "$STOP_ON_FAILURE" = true ]; then
-              stop
-              exit 7
-            fi
-          fi
+
+          check_dagrun_result "${DAG_ID}"
+          exit ${?}
         fi
       fi
     fi
