Add timeout to wait for airflow UI to prevent infinite loop

diff --git a/whirl b/whirl
--- a/whirl
+++ b/whirl
@@ -169,9 +169,20 @@ start() {
     docker-compose -f "${ENVIRONMENT_FOLDER}/docker-compose.yml" up ${DAEMON} --build --force-recreate
 
     if [ "${CI_MODE}" == true ]; then
+      wait_period=0
       while [[ "$(curl -s -o /dev/null -w %\{http_code\} http://localhost:${AIRFLOW_UI_PORT})" != "302" ]]; do
         echo "Waiting for Airflow UI to come up..."
-        sleep 10;
+        if [ $wait_period -ge 120 ]; then
+          status_code=$(curl -s -o /dev/null -w %\{http_code\} http://localhost:${AIRFLOW_UI_PORT})
+          echo "Been waiting for airflow to start for 2 minutes. Aborting now..."
+          echo "Current HTTP status of http://localhost:${AIRFLOW_UI_PORT} is ${status_code}"
+          debug_log_airflow
+          stop
+          exit 3
+        else
+          wait_period=$(($wait_period+10))
+          sleep 10;
+        fi
       done
       sleep 10;
       if [[ "$(curl -s -o /dev/null -w %\{http_code\} -X PATCH  -H 'Content-Type: application/json' --user admin:admin "http://localhost:${AIRFLOW_UI_PORT}/api/v1/dags/${DAG_ID}?update_mask=is_paused" -d '{ "is_paused": false }')" != "200" ]]; then
@@ -181,7 +192,7 @@ start() {
         curl -X PATCH  -H 'Content-Type: application/json' --user admin:admin "http://localhost:${AIRFLOW_UI_PORT}/api/v1/dags/${DAG_ID}?update_mask=is_paused" -d '{ "is_paused": false }'
         debug_log_airflow
         stop
-        exit 3
+        exit 5
       else
         echo "Unpaused dag with id ${DAG_ID}."
         sleep 5;
@@ -215,7 +226,7 @@ start() {
           debug_log_airflow
           if [ "$STOP_ON_FAILURE" = true ]; then
             stop
-            exit 2
+            exit 7
           fi
         fi
       fi
@@ -244,7 +255,7 @@ usage() {
   echo "  start|stop                         start or stop all"
   echo "  ci                                 runs in daemonized mode and awaits dag run completion"
   echo "  -i|--dag_id dag_id                 specify the dag_id to check (only in ci mode)"
-  exit 1
+  exit 21
 }
 
 function read_arguments() {
